Práctica 1 - Grupo #8/Models/ErrorViewModel.cs
namespace Práctica_1___Grupo__8.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Práctica 1 - Grupo #8/Controllers/AutenticacionController.cs
using Microsoft.AspNetCore.Mvc;

namespace Práctica_1___Grupo__8.Controllers
{
    public class AutenticacionController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Registro()
        {
            return View();
        }

        public IActionResult RecuperarContrasennia()
        {
            return View();
        }
    }
}

Práctica 1 - Grupo #8/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace Práctica_1___Grupo__8.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Práctica 1 - Grupo #8/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Práctica_1___Grupo__8.Models;

namespace Práctica_1___Grupo__8.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Práctica 1 - Grupo #8/Views/Autenticacion/Login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutExterno.cshtml";
}
<div class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-dark navbar-extend p-2" style="background-color: #291410;">
        <div class="container-fluid">
            <a class="navbar-brand fs-4 fw-bold">
                <i class="fa fa-heart mx-2"></i> Donde tu belleza encuentra su mejor versión.
            </a>
        </div>
    </nav>
    <section class="container-fluid d-flex flex-grow-1 px-0">
        <div class="col">
            <img src="https://images.pexels.com/photos/8467976/pexels-photo-8467976.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="img-fluid" style="object-fit: cover; height: 100%">
        </div>
        <div class="col d-flex align-items-center">
            <div class="container-fluid d-flex flex-column">
                <form class="pb-5 border-bottom px-5" method="POST">
                    <div class="text-center fw-bold" style="font-size: 10vh; color: #321914;">AgendaTuLook</div>
                    <h2 class="mb-5 text-center" style="color: #321914;">Ingresar</h2>
                    <div class="form-group form-floating pb-3">
                        <input type="text" class="form-control" placeholder="Cédula" name="Cédula" id="Cédula" />
                        <label class="form-label">Cédula</label>
                    </div>
                    <div class="form-group form-floating pb-3">
                        <input type="password" class="form-control" placeholder="Contraseña" name="password" id="password" />
                        <label class="form-label">Contraseña</label>
                    </div>
                    <div class="form-group text-center">
                        <a href="@Url.Action("Index", "Home")" class="btn btn-lg btn-primary w-100" style="background-color:#321914; border-color: #1F283E;">
                            Iniciar Sesión
                        </a>
                        <div class="mt-3">
                            <p style=" color: #321914;">O inicia con: </p>
                        </div>
                        <div class="btn w-75 pb-2" style="background-color:#FAF9F6; border-color: #1F283E;">
                            <a href="@Url.Action("Index", "Home")" class="text-secondary text-decoration-none">
                                <i>
                                    <img src="https://png.pngtree.com/png-vector/20230817/ourmid/pngtree-google-internet-icon-vector-png-image_9183287.png"
                                         width="30" />
                                </i>
                                Google
                            </a>
                        </div>
                        <div class=" btn w-75 shadow mt-2" style="background-color:#1178f2; border-color: #1F283E;">
                            <a href="@Url.Action("Index", "Home")" class="text-white text-decoration-none">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/768px-Facebook_Logo_%282019%29.png" width="30" class="pb-1" />
                                Facebook
                            </a>
                        </div>
                        
                    </div>
                </form>
                <div class="mt-3 text-center">
                    <a href="@Url.Action("RecuperarContrasennia", "Autenticacion")" class="mt-5 text-center under">¿Olvidó su contraseña?</a>
                </div>
                <a href="@Url.Action("Registro", "Autenticacion")" class="mt-4 text-center under">¿No tenés Cuenta? <br> ¡Crea una ya! </a>
            </div>
        </div>
    </section>
</div>

Práctica 1 - Grupo #8/Views/Autenticacion/RecuperarContrasennia.cshtml
@{
    Layout = "~/Views/Shared/_LayoutExterno.cshtml";
}
<div class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-dark navbar-expand p-2" style="background-color: #1A2035;">
        <div class="container-fluid">
            <a class="navbar-brand fs-4 fw-bold" href="@Url.Action("Login", "Usuario")">
                <i class="fa fa-heart mx-2"></i> Donde tu belleza encuentra su mejor versión.
            </a>
        </div>
    </nav>
    <section class="container-fluid d-flex flex-grow-1 px-0">
        <div class="col">
            <img src="https://images.pexels.com/photos/29141596/pexels-photo-29141596/free-photo-of-retrato-creativo-con-afro-azul-y-unas-artisticas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="img-fluid" style="object-fit: cover; height: 100%;" />
        </div>
        <div class="col d-flex align-items-center">
            <div class="container-fluid d-flex flex-column">
                <form class="pb-5 border-bottom px-5" asp-action="RecuperarCuenta" method="post">
                    <div class="text-center fw-bold" style="font-size: 10vh; color: #1F283E;">AgendaTuLook</div>
                    <h2 class="mb-3 text-center" style="color: #1F283E;">Recuperación de Contraseña</h2>
                    <p class="mb-4 text-center">Ingresá tu usuario para iniciar el proceso de recuperación.</p>
                    <div class="form-group form-floating mb-4">
                        <label for="Cedula">Cédula</label>
                        <input type="text" class="form-control" id="Cedula" required />
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary btn-lg" style="background-color:#1F283E; border-color: #1F283E;">
                            Recuperar
                        </button>
                    </div>
                </form>
                <a href="@Url.Action("Registro", "Autenticacion")" class="mt-4 text-center">¿No tenés Cuenta? <br> ¡Crea una ya!</a>
                <a href="@Url.Action("Login", "Autenticacion")" class="mt-4 text-center">Si ya tenés una cuenta, <br> Iniciá Sesión</a>
            </div>
        </div>
    </section>
</div>

Práctica 1 - Grupo #8/Views/Autenticacion/Registro.cshtml
@{
    Layout = "~/Views/Shared/_LayoutExterno.cshtml";
}
<div class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-dark navbar-extend p-2" style="background-color: #291410;">
        <div class="container-fluid">
            <a class="navbar-brand fs-4 fw-bold" th:href="">
                <i class="fa fa-heart mx-2"></i> Donde tu belleza encuentra su mejor versión.
            </a>
        </div>
    </nav>
    <section class="container-fluid d-flex flex-grow-1 px-0">
        <div class="col">
            <img src="https://images.pexels.com/photos/3993123/pexels-photo-3993123.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="img-fluid" style="object-fit: cover; height: 100%">
        </div>
        <div class="col d-flex align-items-center">
            <div class="container-fluid d-flex flex-column">
                <form class="pb-4 border-bottom px-5" th:action="" method="POST">
                    <div class="text-center fw-bold" style="font-size: 10vh; color: #321914;">AgendaTuLook</div>
                    <h2 class="mb-5 text-center" style="color: #321914;">Registrarse</h2>

                    <div class="row g-4 pb-3">
                        <div class="col-12">
                            <div class="form-group form-floating">
                                <input type="text" class="form-control" placeholder="Cédula" name="Cédula" id="Cédula"/>
                                <label class="form-label">Cédula</label>
                            </div>
                        </div>
                    </div>

                    <div class="row g-4 pb-3">
                        <div class="col-md-5">
                            <div class="form-group form-floating">
                                <input type="text" class="form-control" placeholder="Nombre" name="Nombre" id="Nombre" readonly />
                                <label class="form-label">Nombre</label>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group form-floating">
                                <input type="text" class="form-control" placeholder="Apellidos" name="Apellidos" id="Apellidos" readonly />
                                <label class="form-label">Apellidos</label>
                            </div>
                        </div>
                    </div>

                    <div class="row g-4 pb-3">
                        <div class="col-md-6">
                            <div class="form-group form-floating">
                                <select class="form-select" name="Genero" id="Genero" aria-label="Género">
                                    <option selected disabled>Seleccione su género</option>
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                    <option value="Otro">Otro</option>
                                    <option value="Prefiero no decir">Prefiero no decir</option>
                                </select>
                                <label class="form-label">Género</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group form-floating">
                                <input type="text" class="form-control" placeholder="Número Telefónico" name="Telefono" id="Telefono" />
                                <label class="form-label">Número Telefónico</label>
                            </div>
                        </div>
                    </div>

                    <div class="row g-4">
                        <div class="col-md-6">
                            <div class="form-group form-floating">
                                <input type="email" class="form-control" placeholder="Correo Electrónico" name="Email" id="Email" />
                                <label class="form-label">Correo Electrónico</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group form-floating">
                                <input type="password" class="form-control" placeholder="Contraseña" name="password" id="password" />
                                <label class="form-label">Contraseña</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group text-center mt-4">
                        <a href="@Url.Action("Index", "Home")" class="btn btn-primary w-100 btn-lg" style="background-color:#321914; border-color: #321914;">
                            Registrarse
                        </a>
                        <div class="pt-2">
                            <p style=" color: #321914;">Puedes crear una cuenta con:</p>
                        </div>
                        <div class="btn w-75 pb-2" style="background-color:#FAF9F6; border-color: #1F283E;">
                            <a href="@Url.Action("Index", "Home")" class="text-secondary text-decoration-none">
                                <i>
                                    <img src="https://png.pngtree.com/png-vector/20230817/ourmid/pngtree-google-internet-icon-vector-png-image_9183287.png"
                                         width="30" />
                                </i>
                                Google
                            </a>
                        </div>
                        <div class=" btn w-75 shadow mt-2" style="background-color:#1178f2; border-color: #1F283E;">
                            <a href="@Url.Action("Index", "Home")" class="text-white text-decoration-none">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/768px-Facebook_Logo_%282019%29.png" width="30" class="pb-1" />
                                Facebook
                            </a>
                        </div>
                    </div>
                </form>
                <a href="@Url.Action("Login", "Autenticacion")" class="mt-4 text-center under">¿Ya tenés una cuenta? <br> ¡Inicia sesión aquí!</a>
            </div>
        </div>
    </section>
</div>

Práctica 1 - Grupo #8/Views/Home/Index.cshtml
<div id="carouselExampleControls" class="carousel slide mb-3" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active position-relative">
            <img src="https://images.squarespace-cdn.com/content/v1/5fd787d32a8a4a2604b22b5d/a1a982a2-8886-4017-a735-3fde5aeab145/msbs-barbershop-perspective-22000.jpg"
                 class="d-block w-100" height="300px" style="object-fit: cover">
            <div class="position-absolute top-0 start-0 w-100 h-100 bg-dark bg-opacity-50 d-flex justify-content-center align-items-center">
                <h2 class="text-white">CTA</h2>
            </div>
        </div>
        <div class="carousel-item position-relative">
            <img src="https://images.squarespace-cdn.com/content/v1/59a04de337c581c5e1bcd854/1710998377547-DWXDZA5WIX8Q9VKFF0WC/AAA01567.jpg?format=1500w"
                 class="d-block w-100" height="300px" style="object-fit: cover">
            <div class="position-absolute top-0 start-0 w-100 h-100 bg-dark bg-opacity-50 d-flex justify-content-center align-items-center">
                <h2 class="text-white">CTA</h2>
            </div>
        </div>
        <div class="carousel-item position-relative">
            <img src="https://cdn.prod.website-files.com/644a9d9ce529ef8812f82a28/647fb85c69e95444243ef9bd_Henley%27s%20Gentlemen%27s%20Grooming%20-%20Barbershop%20and%20Mens%20Grooming.webp"
                 class="d-block w-100" height="300px" style="object-fit: cover">
            <div class="position-absolute top-0 start-0 w-100 h-100 bg-dark bg-opacity-50 d-flex justify-content-center align-items-center">
                <h2 class="text-white">CTA</h2>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>



<h1 style="font-size: 2vh;" class="fw-bold"> Accesos Rápidos</h1>
<div class="row">
    <div class="col-3">
        <a class="card text-decoration-none border border-1 shadow-sm">
            <div class="card-body text-center">
                <i class="align-middle mb-2 fas fa-calendar-plus fa-2x text-black"></i>
                <h5 class="card-title mb-0">Opción 1</h5>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a class="card text-decoration-none border border-1 shadow-sm">
            <div class="card-body text-center">
                <i class="align-middle mb-2 fas fa-calendar-check fa-2x text-black"></i>
                <h5 class="card-title mb-0">Opción 2</h5>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a class="card text-decoration-none border border-1 shadow-sm">
            <div class="card-body text-center">
                <i class="align-middle mb-2 fas fa-calendar-check fa-2x text-black"></i>
                <h5 class="card-title mb-0">Opción 3</h5>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a class="card text-decoration-none border border-1 shadow-sm">
            <div class="card-body text-center">
                <i class="align-middle mb-2 fas fa-calendar-check fa-2x text-black"></i>
                <h5 class="card-title mb-0">Opción 4</h5>
            </div>
        </a>
    </div>
</div>

Práctica 1 - Grupo #8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>AgendaTuLook</title>
	<link href="~/css/app.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
                <a class="sidebar-brand pb-0 text-decoration-none" href="#">
                    <span class="align-middle text-white fw-bold fs-3">AgendaTuLook</span>
                </a>

                <ul class="sidebar-nav">
					<li class="sidebar-header">
						Opciones de Admin
					</li>

					<li class="sidebar-item active">
						<a class="sidebar-link" href="index.html">
							<i class="align-middle fas fa-home"></i> <span class="align-middle">Inicio</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-calendar-alt"></i> <span class="align-middle">Mi Calendario</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-calendar-check"></i> <span class="align-middle">Gestionar Citas</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-users"></i> <span class="align-middle">Gestionar personal</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-chart-bar"></i> <span class="align-middle">Estadísticas</span>
						</a>
					</li>

					<li class="sidebar-header">
						Opciones de Cliente
					</li>

					<li class="sidebar-item active">
						<a class="sidebar-link" href="index.html">
							<i class="align-middle fas fa-home"></i> <span class="align-middle">Inicio</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-calendar-alt"></i> <span class="align-middle">Mi Calendario</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-calendar-plus"></i> <span class="align-middle">Solicitar Cita</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-history"></i> <span class="align-middle">Historial de Citas</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle fas fa-ticket-alt"></i> <span class="align-middle">Mis Cupones</span>
						</a>
					</li>

                </ul>
			</div>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
					<i class="hamburger align-self-center"></i>
				</a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-bs-toggle="dropdown">
								<div class="position-relative">
									<i class="align-middle" data-feather="bell"></i>
									<span class="indicator">4</span>
								</div>
							</a>
							<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
								<div class="dropdown-menu-header">
									4 New Notifications
								</div>
								<div class="list-group">
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-danger" data-feather="alert-circle"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Update completed</div>
												<div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
												<div class="text-muted small mt-1">30m ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-warning" data-feather="bell"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Lorem ipsum</div>
												<div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
												<div class="text-muted small mt-1">2h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-primary" data-feather="home"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Login from 192.186.1.8</div>
												<div class="text-muted small mt-1">5h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-success" data-feather="user-plus"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">New connection</div>
												<div class="text-muted small mt-1">Christina accepted your request.</div>
												<div class="text-muted small mt-1">14h ago</div>
											</div>
										</div>
									</a>
								</div>
								<div class="dropdown-menu-footer">
									<a href="#" class="text-muted">Show all notifications</a>
								</div>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
								<i class="align-middle" data-feather="settings"></i>
							</a>

							<a class="nav-link d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                                <img src="https://st3.depositphotos.com/9998432/13335/v/450/depositphotos_133352010-stock-illustration-default-placeholder-man-and-woman.jpg" class="avatar img-fluid rounded me-1" /> 
                                <span class="text-dark">Usuario</span>
                                <i class="align-middle fas fa-chevron-down"></i>
							</a>
							<div class="dropdown-menu dropdown-menu-end">
                                <a class="dropdown-item"><i class="align-middle me-1 fas fa-cog"></i> Ajustes</a>
								<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("Login", "Autenticacion")">
                                    <i class="align-middle me-1 fas fa-sign-out-alt"></i> Salir
                                </a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<main class="content">
				<div class="container-fluid p-0">

					@RenderBody()
				</div>
			</main>
			<footer class="footer">
				<div class="container-fluid">
					<div class="row text-muted">
						<div class="col-6 text-start">
							<p class="mb-0">
								<a class="text-muted" href="#"><strong>Proyecto</strong></a> &copy;
							</p>
						</div>
						<div class="col-6 text-end">
							<ul class="list-inline">
								<li class="list-inline-item">
									<a class="text-muted" href="#" target="_blank">Link</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>
	<script src="~/js/app.js"></script>
</body>
</html>

Práctica 1 - Grupo #8/Views/Shared/_LayoutExterno.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>AgendaTuLook</title>
    <meta charset="UTF-8" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body class="d-flex flex-column min-vh-100">
    @RenderBody()
    
</body>
</html>